### ISSUE TITLE
Typescript compiler can't read or compile types

### ISSUE THREAD

**Issue by Kaleb47** [TempleDAO/temple#521]
### Description

ok so I was able to successfully build the protocol directory and deploy the temple token to testnet. The problem is when running any of the other deploy scripts within the  `scripts/deploys/rinkeby`, it doesn't recognize any of the types.

When I deploy the staking contracts

```
TSError: ⨯ Unable to compile TypeScript:
scripts/deploys/helpers.ts:56:3 - error TS2741: Property 'EXIT_QUEUE' is missing in type '{ PRESALE_ALLOCATION: string; PRESALE: string; SANDALWOOD_TOKEN: string; OPENING_CEREMONY: string; OPENING_CEREMONY_VERIFIER: string; AMM_WHITELIST: string; FRAX: string; TEMPLE: string; ... 22 more ...; MULTISIG: string; }' but required in type 'DeployedContracts'.

56   rinkeby: {
     ~~~~~~~

  scripts/deploys/helpers.ts:5:3
    5   EXIT_QUEUE: string;
        ~~~~~~~~~~
    'EXIT_QUEUE' is declared here.
  scripts/deploys/helpers.ts:55:35
    55 export const DEPLOYED_CONTRACTS: {[key: string]: DeployedContracts} = {
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from this index signature.
scripts/deploys/helpers.ts:100:3 - error TS2741: Property 'EXIT_QUEUE' is missing in type '{ PRESALE_ALLOCATION: string; PRESALE: string; SANDALWOOD_TOKEN: string; OPENING_CEREMONY: string; OPENING_CEREMONY_VERIFIER: string; FRAX: string; MULTISIG: string; TEMPLE: string; STAKING: string; ... 21 more ...; VAULT_PROXY: string; }' but required in type 'DeployedContracts'.

100   mainnet: {
      ~~~~~~~

  scripts/deploys/helpers.ts:5:3
    5   EXIT_QUEUE: string;
        ~~~~~~~~~~
    'EXIT_QUEUE' is declared here.
  scripts/deploys/helpers.ts:55:35
    55 export const DEPLOYED_CONTRACTS: {[key: string]: DeployedContracts} = {
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from this index signature.
scripts/deploys/helpers.ts:144:3 - error TS2741: Property 'EXIT_QUEUE' is missing in type '{ PRESALE_ALLOCATION: string; PRESALE: string; SANDALWOOD_TOKEN: string; OPENING_CEREMONY: string; OPENING_CEREMONY_VERIFIER: string; FRAX: string; TEMPLE: string; STAKING: string; LEGACY_LOCKED_OG_TEMPLE: string; ... 21 more ...; MULTISIG: string; }' but required in type 'DeployedContracts'.

144   localhost: {
      ~~~~~~~~~

  scripts/deploys/helpers.ts:5:3
    5   EXIT_QUEUE: string;
        ~~~~~~~~~~
    'EXIT_QUEUE' is declared here.
  scripts/deploys/helpers.ts:55:35
    55 export const DEPLOYED_CONTRACTS: {[key: string]: DeployedContracts} = {
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from this index signature.

    at createTSError (/workspace/Temple-DAO/protocol/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/workspace/Temple-DAO/protocol/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/workspace/Temple-DAO/protocol/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/workspace/Temple-DAO/protocol/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/workspace/Temple-DAO/protocol/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/workspace/Temple-DAO/protocol/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: "\x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m56\x1B[0m:\x1B[93m3\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2741: \x1B[0mProperty 'EXIT_QUEUE' is missing in type '{ PRESALE_ALLOCATION: string; PRESALE: string; SANDALWOOD_TOKEN: string; OPENING_CEREMONY: string; OPENING_CEREMONY_VERIFIER: string; AMM_WHITELIST: string; FRAX: string; TEMPLE: string; ... 22 more ...; MULTISIG: string; }' but required in type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m56\x1B[0m   rinkeby: {\n' +
    '\x1B[7m  \x1B[0m \x1B[91m  ~~~~~~~\x1B[0m\n' +
    '\n' +
    '  \x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m5\x1B[0m:\x1B[93m3\x1B[0m\n' +
    '    \x1B[7m5\x1B[0m   EXIT_QUEUE: string;\n' +
    '    \x1B[7m \x1B[0m \x1B[96m  ~~~~~~~~~~\x1B[0m\n' +
    "    'EXIT_QUEUE' is declared here.\n" +
    '  \x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m55\x1B[0m:\x1B[93m35\x1B[0m\n' +
    '    \x1B[7m55\x1B[0m export const DEPLOYED_CONTRACTS: {[key: string]: DeployedContracts} = {\n' +
    '    \x1B[7m  \x1B[0m \x1B[96m                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n' +
    '    The expected type comes from this index signature.\n' +
    "\x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m100\x1B[0m:\x1B[93m3\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2741: \x1B[0mProperty 'EXIT_QUEUE' is missing in type '{ PRESALE_ALLOCATION: string; PRESALE: string; SANDALWOOD_TOKEN: string; OPENING_CEREMONY: string; OPENING_CEREMONY_VERIFIER: string; FRAX: string; MULTISIG: string; TEMPLE: string; STAKING: string; ... 21 more ...; VAULT_PROXY: string; }' but required in type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m100\x1B[0m   mainnet: {\n' +
    '\x1B[7m   \x1B[0m \x1B[91m  ~~~~~~~\x1B[0m\n' +
    '\n' +
    '  \x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m5\x1B[0m:\x1B[93m3\x1B[0m\n' +
    '    \x1B[7m5\x1B[0m   EXIT_QUEUE: string;\n' +
    '    \x1B[7m \x1B[0m \x1B[96m  ~~~~~~~~~~\x1B[0m\n' +
    "    'EXIT_QUEUE' is declared here.\n" +
    '  \x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m55\x1B[0m:\x1B[93m35\x1B[0m\n' +
    '    \x1B[7m55\x1B[0m export const DEPLOYED_CONTRACTS: {[key: string]: DeployedContracts} = {\n' +
    '    \x1B[7m  \x1B[0m \x1B[96m                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n' +
    '    The expected type comes from this index signature.\n' +
    "\x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m144\x1B[0m:\x1B[93m3\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2741: \x1B[0mProperty 'EXIT_QUEUE' is missing in type '{ PRESALE_ALLOCATION: string; PRESALE: string; SANDALWOOD_TOKEN: string; OPENING_CEREMONY: string; OPENING_CEREMONY_VERIFIER: string; FRAX: string; TEMPLE: string; STAKING: string; LEGACY_LOCKED_OG_TEMPLE: string; ... 21 more ...; MULTISIG: string; }' but required in type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m144\x1B[0m   localhost: {\n' +
    '\x1B[7m   \x1B[0m \x1B[91m  ~~~~~~~~~\x1B[0m\n' +
    '\n' +
    '  \x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m5\x1B[0m:\x1B[93m3\x1B[0m\n' +
    '    \x1B[7m5\x1B[0m   EXIT_QUEUE: string;\n' +
    '    \x1B[7m \x1B[0m \x1B[96m  ~~~~~~~~~~\x1B[0m\n' +
    "    'EXIT_QUEUE' is declared here.\n" +
    '  \x1B[96mscripts/deploys/helpers.ts\x1B[0m:\x1B[93m55\x1B[0m:\x1B[93m35\x1B[0m\n' +
    '    \x1B[7m55\x1B[0m export const DEPLOYED_CONTRACTS: {[key: string]: DeployedContracts} = {\n' +
    '    \x1B[7m  \x1B[0m \x1B[96m                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\x1B[0m\n' +
    '    The expected type comes from this index signature.\n',
  diagnosticCodes: [ 2741, 2741, 2741 ]
}
```

or the amm

```
TSError: тип Unable to compile TypeScript:
scripts/deploys/rinkeby/20-deploy-ops-manager.ts:53:83 - error TS2339: Property 'STAKING' does not exist on type 'DeployedContracts'.

53     const templeStaking = await new TempleStaking__factory(owner).attach(DEPLOYED.STAKING);
                                                                                     ~~~~~~~
scripts/deploys/rinkeby/20-deploy-ops-manager.ts:61:26 - error TS2339: Property 'STAKING' does not exist on type 'DeployedContracts'.

61                 DEPLOYED.STAKING,
                            ~~~~~~~
scripts/deploys/rinkeby/20-deploy-ops-manager.ts:62:26 - error TS2339: Property 'FAITH' does not exist on type 'DeployedContracts'.

62                 DEPLOYED.FAITH
                            ~~~~~
scripts/deploys/rinkeby/20-deploy-ops-manager.ts:69:26 - error TS2339: Property 'STAKING' does not exist on type 'DeployedContracts'.

69                 DEPLOYED.STAKING,
                            ~~~~~~~
scripts/deploys/rinkeby/20-deploy-ops-manager.ts:74:45 - error TS2339: Property 'STAKING' does not exist on type 'DeployedContracts'.

74     console.log(`Temple Staking: ${DEPLOYED.STAKING}`);
                                               ~~~~~~~

    at createTSError (/Users/kalebamarante/monorepo/protocol/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/kalebamarante/monorepo/protocol/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/Users/kalebamarante/monorepo/protocol/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/Users/kalebamarante/monorepo/protocol/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/Users/kalebamarante/monorepo/protocol/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/kalebamarante/monorepo/protocol/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticText: "\x1B[96mscripts/deploys/rinkeby/20-deploy-ops-manager.ts\x1B[0m:\x1B[93m53\x1B[0m:\x1B[93m83\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'STAKING' does not exist on type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m53\x1B[0m     const templeStaking = await new TempleStaking__factory(owner).attach(DEPLOYED.STAKING);\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                                                                                  ~~~~~~~\x1B[0m\n' +
    "\x1B[96mscripts/deploys/rinkeby/20-deploy-ops-manager.ts\x1B[0m:\x1B[93m61\x1B[0m:\x1B[93m26\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'STAKING' does not exist on type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m61\x1B[0m                 DEPLOYED.STAKING,\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                         ~~~~~~~\x1B[0m\n' +
    "\x1B[96mscripts/deploys/rinkeby/20-deploy-ops-manager.ts\x1B[0m:\x1B[93m62\x1B[0m:\x1B[93m26\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'FAITH' does not exist on type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m62\x1B[0m                 DEPLOYED.FAITH\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                         ~~~~~\x1B[0m\n' +
    "\x1B[96mscripts/deploys/rinkeby/20-deploy-ops-manager.ts\x1B[0m:\x1B[93m69\x1B[0m:\x1B[93m26\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'STAKING' does not exist on type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m69\x1B[0m                 DEPLOYED.STAKING,\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                         ~~~~~~~\x1B[0m\n' +
    "\x1B[96mscripts/deploys/rinkeby/20-deploy-ops-manager.ts\x1B[0m:\x1B[93m74\x1B[0m:\x1B[93m45\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2339: \x1B[0mProperty 'STAKING' does not exist on type 'DeployedContracts'.\n" +
    '\n' +
    '\x1B[7m74\x1B[0m     console.log(`Temple Staking: ${DEPLOYED.STAKING}`);\n' +
    '\x1B[7m  \x1B[0m \x1B[91m                                            ~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2339, 2339, 2339, 2339, 2339 ]
}
```

Its like someone forgot to add the types to the index.ts.

**Comment by scooprinder** [comment]
thanks for creating the issue @Kaleb47 - the typechain is being generated correctly - the reason the script is failing is because the deployed contracts keys are not present in the DeployedContract object (see https://github.com/TempleDAO/temple/blob/stage/protocol/scripts/deploys/helpers.ts). 

The deploys dir on the protocol is something that has been built over time and relies on updating the `helper.ts` inbetween each deploy. It's not suitable for just running scripts in sequence. We have a couple of tickets that'll help address this (#434 #446 ). 

If you're attempting to deploy the stack to test, I'd suggest trying with the local hardhat deploy - see https://github.com/TempleDAO/temple/blob/stage/protocol/scripts/local-dapp-dev/deploy.ts 

This can be run by running `yarn local-node` in one terminal to bring up an instance of hardhat EVM and then running `yarn local-deploy` in another to deploy these contracts locally.

**Comment by scooprinder** [comment]
Hey @Kaleb47 I'm going to close this as the issue is stale - please do let me know if you feel this is a mistake.
